### PR TITLE
fix(conference-call): passing a wrong json format to AVS

### PR DESCRIPTION
**Pull request by ohassine**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

In clients handler, the json of clients  that we pass to AVS is encoded with an incorrect format 

Wrong passed JSON:
```
[ { userid: "value", clientid: "" } ]
```
Correct format:
```
{ clients: [ { userid: "value", clientid: "" } ] }
```

### Solutions

Fix that =)

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

Nothing visible to test

#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by alexandreferris — APPROVED** [review]
👏🏻 nice catch

**Comment by vitorhugods** [comment]
Out of curiosity, what would be the `wrong` and `correct` format?

Can we document it somewhere so our future-selves and team-mates can figure it out more easily?

**Comment by alexandreferris** [comment]
> 

From my understading we were sending just the list of clients and not a object which its param was a list of clients, right? 🤔

**Review by yamilmedina — APPROVED** [review]
LGTM! 🚀

**Comment by ohassine** [comment]
> Out of curiosity, what would be the `wrong` and `correct` format?
> 
> Can we document it somewhere so our future-selves and team-mates can figure it out more easily?

I updated the description by adding the wrong and correct format.

As Alexander said we were sending a list of object while we have to send an object of clients.
For documentation I would suggest to do it later, we have to document many things related to calling including this one

**Pull request merged**
