### PR TITLE
feat: build configs [AR-1463]

### PR DESCRIPTION
**Pull request by MohammedMokresh**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues
generate build configs from the local default.json or from remote repo if exist
----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by vitorhugods** [comment]
I have some questions here. The PR template has a section called `solutions` that is quite helpful, so that could've prevented these:

## 1. In general, how to use it?

Is this a `Kalium` thing? Can we use it directly on Reloaded?
Do we need to rebuild Kalium if we want different feature flags? What 

## 2. What about multiple clients?

If I want to build Reloaded A and Reloaded B with different feature flags, what should I do?

## 3. Baseline.xml?

Why add _more_ stuff to the baseline? The idea behind this file was that we could introduce the style checker without it failing due to current issues.
After Detekt was added, we should only **remove** from the Baseline as we fix the problems, not introduce more.


----

In general, I was thinking that we could have a code / flags generator that reads from Json and exports as global stuff, however if we need to do this

**Comment by vitorhugods** [comment]
In general, I am not sure how much it's Kalium's responsibility for reading JSON and turning them into flags. At least to some degree it can work (for Android and JVM for example), not sure about generating stuff that is accessible to Swift and JS.

At times, we might need config flags on each client too, as we want to hide some feature that is being developed, or some custom UI stuff that is app/platform-specific.

One thing I am certain: Kalium could and should have feature flags, so this is centralised across all platforms:

```kotlin
data class FeatureFlags(
    val isSSOEnabled: Boolean,
    val isSendingAssetsEnabled: Boolean
)

class ObserveFeatureFlagsUseCase {
    suspend operator fun invoke(): Flow<FeatureFlags>
}
```

The apps when building could read from a Json file, or whatever else they want, and when creating `CoreLogic`, could pass a `FeatureFlagsConfig`.

Maybe we could provide a Json parser, but I am not sure much we can do for all platforms.
Especially if this means re-building Kalium.

I am also not sure if iOS, JVM or even Android will consume Kalium as a git submodule or we will start deploying Kalium builds and version it once everything is stable.

**Comment by MohammedMokresh** [comment]
@vitorhugods 
> ## 1. In general, how to use it?
As of this PR , it focus on generating the configs , about how to use it we can expose this submodule to the project that need to use either the logic module or the reloaded , but after reading your second comment , now I remembered that we have those features flag that comes from the endpoint , so I think this build config will only be exposed to logic and we merge it with the user flags and we have that use case which will be used in reloaded or other platforms 

> ## 2. What about multiple clients?
maybe I didn't understand properly here , but these configs are generated from the default.json , or from the remote if exist , so if you have another client that need different feature flags , you need to update those json files and build to generate the new flags 

> ## 3. Baseline.xml?
yeah this one on me , because I wanted to use the enum values as it is , I should just update to UPPER_CASE with name and use it , will update that

**Comment by MohammedMokresh** [comment]
> In general, I am not sure how much it's Kalium's responsibility for reading JSON and turning them into flags. At least to some degree it can work (for Android and JVM for example), not sure about generating stuff that is accessible to Swift and JS.
> 
> At times, we might need config flags on each client too, as we want to hide some feature that is being developed, or some custom UI stuff that is app/platform-specific.


for a different client we can generate targeted build configs and maybe after that do like what you mentioned , create a use case for it and use it

**Pull request closed without merging**
