### PR TITLE
fix: show message after removing conversation member (AR-2038)

### PR DESCRIPTION
**Pull request by Garzas**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Message is only showed when user leaves conversation, but not where we are removing other user from conversation

### Solutions

Disable checking if selfUser left conversation

### CODE REVIEW

**Review by gongracr — APPROVED** [review]
It seems backend also doesn't forward these kind of events via the websocket.

Strange enough, seems that the same error happens when the self user is the one adding other users in a group where he is admin. If you could also add it we would kill 2 🐦 with 1 🗿 here but I also understand that falls a bit out of the scope of this PR. 

Good catch in any case 🦅

**Comment by typfel** [comment]
I don't have the full context but generally the backend doesn't forward events on the websocket for the client which performs an action. The client performing the action expected to update his/her local state from the response of the action he/her performed. 

NOTE:  that the event will be returned from the /notifications on the next incremental sync though.

**Comment by gongracr** [comment]
so @typfel you are saying that if we create the event id "on the fly", on next incremental sync we will observe that event duplicated as they will have different ids?

**Comment by typfel** [comment]
> so @typfel you are saying that if we create the event id "on the fly", on next incremental sync we will observe that event duplicated as they will have different ids?

Yes, generally there needs to be some filter in place depending on context. For example:  insert system message for user being removed unless user has already been removed from the group.

**Review by MohamadJaara — APPROVED** [review]

**Pull request merged**
