### PR TITLE
style: Add `.editorconfig` file to sync default Kotlin style across dev environments

### PR DESCRIPTION
**Pull request by vitorhugods**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

We're experiencing conflicts and seeing unnecessary line changes in PRs due to very small differences in code-style settings in the IDE settings.

### Causes (Optional)

Things like wildcard import (`import java.util.*`) and max line length, for example.

### Solutions

Since we're using IntelliJ and/or Android Studio for the project, we can introduce `.editorconfig` file to the project.

> The [EditorConfig](https://editorconfig.org/) project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems. 

As talked with @gongracr and @MohamadJaara, the line length could be shortened to 100 or so characters later. But with test names in the `given/when/then` behaviour style, 100+ is a easy number to reach. So for now, 140 lines is accepted. But let's try not to make it so big, shall we?

### Testing

N/A

----
#### PR Post Merge Checklist for internal contributors

 - [X] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by gongracr** [comment]
did you try running the auto format shortcut on the IDE on any given file, let's say the `API.kt` one and see it doesn't reformat everything?

**Comment by vitorhugods** [comment]
Maybe I can include all of these auto format stuff in the PR? So this gets done once and for all?

If I run it in the whole project, there are some changes, but on 98 files. Nothing too crazy.

The main ones are:

Import
----
```kotlin
import java.util.*
```

becomes

```kotlin
import java.util.UUID
```

Identation
----
It seems a lot of the original models had an extra identation compared to what comes shipped with IntelliJ:
```kotlin
data class PreKey(
        val id: Int, //8 spaces for constructor parameters
        val key: String
)

```

becomes

```kotlin
data class PreKey(
    val id: Int,  //4 spaces for constructor parameters
    val key: String
)

```

**Comment by gongracr** [comment]
Yep, if the main cosmetic changes look like that, then I'm happy going forward. 
Re: all the files reformated with the new style in this same PR, I think it's also wise to do it in this same one unless any one else has a different POV

**Review by MohamadJaara — APPROVED** [review]
looks good to me, just remember to rebase any local/ work branches before committing anything new

**Pull request merged**
