### PR TITLE
feat: logout use case

### PR DESCRIPTION
**Pull request by MohamadJaara**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

atm logout does nothing

### Solutions

implementing `LogoutUseCase` that does the following: 
- [x] make logoutApi request to delete the session remotly
- [x] clear user DB
- [x] clear user Preferences
- [x] delete the session locally
- [x] update the current session

Needs releases with:

- [x] #226 

### Testing

WIP

----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by mchenani — APPROVED** [review]
🔥✌️

**Comment by MohamadJaara** [comment]
@ohassine what is logout behaviour in the current app

**Comment by ohassine** [comment]
> @ohassine what is the logout behaviour in the current app

In the current app, a new database is created for every new  logged in user.
we don't delete nor clear the database after user logout

**Comment by vitorhugods** [comment]
> > @ohassine what is the logout behaviour in the current app
> 
> In the current app, a new database is created for every new logged in user. we don't delete nor clear the database after user logout

We just delete the "session"? Without deleting anything else? Like client, etc. etc. ?
That kinda sounds doable.
But depending on how long it has been since the last time you were authenticated, it could mean a lot of events to process. And if there's a bug that "logging out and logging in again" could fix... maybe this wouldn't be possible. 🤔

**Comment by MohamadJaara** [comment]
> There is a corner case that we need to care about: when the user have two logged in accounts 😐

in kalium we create a different DB for each user, that means deleting the DB file for user A will not effect user B

**Comment by ohassine** [comment]
> @MohamadJaara and @ohassine
> 
> Can we scope this down and treat the "recover some data like messages and the like when the user logs in again on the same device" as a different feature?
> 
> That is: for now, we erase everything and we make sure that Logout works.
> 
> If we want to be fancy, we can do it later. That's a different feature.

Alright, we can do it later as different feature.
but this may cost us extra refactoring later.
I have a suggestion: only revoke user session and do not delete the whole database
what do you think ?

**Comment by MohamadJaara** [comment]
@ohassine for now, I will merge the PR as it's and any fancy features we need (e.g. reset user session) can be added in the future. Just to make sure that everything is working as expected.

**Pull request merged**
