### PR TITLE
feat: part-4 refresh session: injecting userId for UserSessionScope and WorkScheduler

### PR DESCRIPTION
**Pull request by MohamadJaara**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

`UserSessionScope` and `WorkScheduler` need `AuthSession` which make it hard to dynamically get the updated session after every refresh 

### Solutions

`SessionManager` + userId

Needs releases with:

- [x] #302 
- [x] #304 
- [x] #306 

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by vitorhugods** [comment]
Github is drunk. Not requiring reviews, nor showing the checks here 🍻

**Review by typfel — APPROVED** [review]
Changes look good to me. Note though when we allow multiple accounts from different backends the user ID is no longer guaranteed to be unique.

Would do we then? Fetch the self user profile initially so that we can have a qualified ID?

**Comment by MohamadJaara** [comment]
@typfel we can daisy-chain requests in `LoginApi` to return a full user Profile + session or ask BE to return a quaQualifiedID on login

**Comment by typfel** [comment]
> @typfel we can daisy-chain requests in `LoginApi` to return a full user Profile + session or ask BE to return a quaQualifiedID on login

👍  let's daisy chain for now then while we wait for BE to return a qualified ID in the login response.

**Comment by MohamadJaara** [comment]
> > @typfel we can daisy-chain requests in `LoginApi` to return a full user Profile + session or ask BE to return a QualifiedID on login
> 
> 👍 let's daisy chain for now then while we wait for BE to return a qualified ID in the login response.

I will do this change in a different PR

**Pull request merged**
