### PR TITLE
feat: Observe self client certificate revocation (WPB-6145)

### PR DESCRIPTION
**Pull request by ohassine**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Description

I this PR, I am creating the logic that will be used in Android to show a dialog when self client's certificate is revoked:

A flag will be observed by Android through a use case called  `ObserveShouldNotifyForRevokedCertificateUseCase` to show the dialog.

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by mchenani — APPROVED** [review]
🔥

**Review by yamilmedina — APPROVED** [review]

**Comment by borichellow** [comment]
Question: how it should work? 
With this implementation user will see the dialog every time he/she launches the app (if the certificate was revoked). 
And (I guess) there is some option to dismiss that dialog (by `MarkNotifyForRevokedCertificateAsNotifiedUseCase`).

But I thought if my certificate was revoked it means that I'm a bad guy and should be logged out, isn't it?

**Comment by ohassine** [comment]
> Question: how it should work? With this implementation user will see the dialog every time he/she launches the app (if the certificate was revoked). And (I guess) there is some option to dismiss that dialog (by `MarkNotifyForRevokedCertificateAsNotifiedUseCase`).
> 
> But I thought if my certificate was revoked it means that I'm a bad guy and should be logged out, isn't it?

Yes we show a dialog recommending to the user to logout.
Check this PR it contains demo video https://github.com/wireapp/wire-android/pull/2594

And once the user dismisses the dialog we invoke `markNotifyForRevokedCertificateAsNotified` so dialog won't show next time

**Comment by borichellow** [comment]
> > Question: how it should work? With this implementation user will see the dialog every time he/she launches the app (if the certificate was revoked). And (I guess) there is some option to dismiss that dialog (by `MarkNotifyForRevokedCertificateAsNotifiedUseCase`).
> > But I thought if my certificate was revoked it means that I'm a bad guy and should be logged out, isn't it?
> 
> Yes we show a dialog recommending to the user to logout. Check this PR it contains demo video [wireapp/wire-android#2594](https://github.com/wireapp/wire-android/pull/2594)
> 
> And once the user dismisses the dialog we invoke `markNotifyForRevokedCertificateAsNotified` so dialog won't show next time

sounds strange to me (the fact the user could skip the logging out), but okay :)

**Pull request merged**
