### PR TITLE
feat: store last generated prekey

### PR DESCRIPTION
**Pull request by MohamadJaara**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

kalium does not store the id of the last generated prekey

### Solutions

store it

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by typfel** [comment]
Why do we need store the ID of the last generated pre key?

**Comment by MohamadJaara** [comment]
> Why do we need store the ID of the last generated pre key?

the scala app is doing so and during the migration i would like to migrate this value too, because the new app will be using the same crypto box files as the old one.

**Comment by typfel** [comment]
> > Why do we need store the ID of the last generated pre key?
> 
> the scala app is doing so and during the migration i would like to migrate this value too, because the new app will be using the same crypto box files as the old one.

Huh interesting but where would you actually use it. Is it some how passed as an argument to crypto box?

**Comment by MohamadJaara** [comment]
> > > Why do we need store the ID of the last generated pre key?
> > 
> > 
> > the scala app is doing so and during the migration i would like to migrate this value too, because the new app will be using the same crypto box files as the old one.
> 
> Huh interesting but where would you actually use it. Is it some how passed as an argument to crypto box?

When generating new prekeys for the backend (we don't do this, atm), 
`ProteusClient.newPrekeys(from: Int, count: Int)`  I'm assuming that the parameter from is `otrLastPrekeyId + 1`

**Review by MohammedMokresh — APPROVED** [review]
LGTM

**Pull request merged**
