### PR TITLE
fix: not updating notifications date in conversations

### PR DESCRIPTION
**Pull request by borichellow**
# What's new in this PR?

### Issues

There was no option to remove the notification, it always came back.

### Causes (Optional)

Updating `last_notified_date` in DB was a bit broken.

### Solutions

Fix updating `last_notified_date` in DB. + removed redundant `Instant->String->Instant` date mapping

### CODE REVIEW

**Review by mchenani — APPROVED** [review]
🦅

**Review by vitorhugods — CHANGES_REQUESTED** [review]
Nice spot, just missing Unit tests to make sure the column `last_notified_date` needs to be null or have a more recent value than `last_modified_date`.

**Comment by borichellow** [comment]
> Nice spot, just missing Unit tests to make sure the column `last_notified_date` needs to be null or have a more recent value than `last_modified_date`.

Yeah, I just wanted to have fix merged before the test-session and work on unit tests meanwhile :) 
But this PR is for `develop` so it can wait.

**Review by vitorhugods — APPROVED** [review]
👨‍🍳👌

**Comment by MohamadJaara** [comment]
no need to merge this PR into dev
i already included this changes in 
https://github.com/wireapp/kalium/pull/1429

**Pull request closed without merging**
