### PR TITLE
fix: update  group state when fetching conversation during slow sync WPB-11247

### PR DESCRIPTION
**Pull request by typfel**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-11247" title="WPB-11247" target="_blank">BugWPB-11247</a>  MLS conversations are broken on client deletion
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Group state isn't updated during the slow sync, which means MLS conversation will keep the `ESTABLISHED` state even though they no longer exists inside CoreCrypto if we registered a new client.

### Causes

`mls_group_state` is not included the "on conflict" clause.

### Solutions

Include it

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by MohamadJaara — APPROVED** [review]

**Comment by vitorhugods** [comment]
It would be nice to add a test for this. Insert a conversation, insert it again with a different mls_group_state and assert that it is updated

**Comment by typfel** [comment]
@MohamadJaara is release/candidate the right destination?

**Comment by MohamadJaara** [comment]
> @MohamadJaara is release/candidate the right destination?

ohh did not notice this one, the correct one should be "release/android-cycle-4.6"

**Comment by typfel** [comment]
> It would be nice to add a test for this. Insert a conversation, insert it again with a different mls_group_state and assert that it is updated

Done

**Pull request merged**
