### PR TITLE
chore: fix dokka issues execution oom

### PR DESCRIPTION
**Pull request by yamilmedina**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

If we run Dokka with stacktrace flag, we found out that is failing because of something similiar to https://github.com/Kotlin/dokka/issues/1405
So this PR tries to solve by suggested actions mentioned there.

- Disabled samples
- Increase memory metaspace and heap for gradle

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by vitorhugods** [comment]
It seems it fails mainly due to `Unresolved reference: otr`:

```
> Task :network:compileCommonMainKotlinMetadata
e: /Users/runner/work/kalium/kalium/network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/message/EnvelopeProtoMapper.kt: (22, 33): Unresolved reference: otr
```

🤔 Curious about this one, considering it usually builds nicely

**Comment by vitorhugods** [comment]
One thing is quite curious:

This problem started EXACTLY when we added `darwin` source sets for `network`, `calling` and `logic` IIRC

**Comment by yamilmedina** [comment]
> One thing is quite curious:
> 
> This problem started EXACTLY when we added `darwin` source sets for `network`, `calling` and `logic` IIRC

Yees ! exactly around that date started, the thing is Dokka seems to have failed in the past with memory management 😓  -like now, having a `StackOverFlowError` so I opened also an issue there, just in case they can help us. https://github.com/Kotlin/dokka/issues/2853

The other thing is to create many partials docs (this seems fine) but would be a bit overkill to merge it later, I think we still can try a couple of things more 🤞

**Comment by yamilmedina** [comment]
I think I'll close this one, as I tried we many approaches, some insights:

- dokka is well known for having bad memory management
- network module is causing a big pain
- executing each task htmlPartial by itself in separate runs, doesn't brake it
- because logic module depends on network, logic never gets to finish running or generating docs.
- excluding cli, logic, and network make it "pass" but loses the point
- maybe is worth taking a shot at https://github.com/adamko-dev/dokkatoo

**Pull request closed without merging**
